# Generated by Django 4.2.13 on 2024-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='discount',
            field=models.IntegerField(default='0', verbose_name='Discount %'),
        ),
    ]
