# Generated by Django 4.2.13 on 2024-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_company_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ref',
            field=models.CharField(max_length=11, unique=True, verbose_name='Generated code'),
        ),
    ]
