# Generated by Django 4.2.13 on 2024-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_company_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validated company'),
        ),
    ]
