# Generated by Django 5.1.5 on 2025-03-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_company_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='countryCode',
            field=models.CharField(default='+216', max_length=4, verbose_name='Country code'),
        ),
    ]
