# Generated by Django 5.1.5 on 2025-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_company_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='countryCode',
            field=models.CharField(default='+216', help_text='Add your country code like +216 or 00216', max_length=5, verbose_name='Country code'),
        ),
    ]
