# Generated by Django 5.1.5 on 2025-03-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_company_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='countryCode',
            field=models.IntegerField(default='00216', help_text='Add your country code like +216 or 00216', verbose_name='Country code'),
        ),
    ]
