# Generated by Django 4.2.16 on 2025-01-20 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdate',
            old_name='max_subscribers',
            new_name='maxSubscribers',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='event_date',
            new_name='eventDate',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
            preserve_default=False,
        ),
    ]
