# Generated by Django 5.1.5 on 2025-01-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_subscriber_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='options',
            field=models.ManyToManyField(blank=True, to='event.eventoption', verbose_name='Event Options'),
        ),
    ]
