# Generated by Django 5.1.5 on 2025-01-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='maxSubscribers',
            field=models.PositiveIntegerField(default=0, verbose_name='Max number of subscribers'),
        ),
    ]
