# Generated by Django 5.1.5 on 2025-01-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_subscriber_eventdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='skydiver_option',
            new_name='skydiverOption',
        ),
    ]
