# Generated by Django 5.1.5 on 2025-01-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_skydiver_option_subscriber_skydiveroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
    ]
