# Generated by Django 5.1.5 on 2025-01-23 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_subscriber_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
