# Generated by Django 5.1.5 on 2025-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_subscriber_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='altitude',
            field=models.CharField(choices=[('3000', '3 000 m (10 000 feet)'), ('3200', '3 200 m (10 500 feet)'), ('3500', '3 500 m (11 500 feet)')], default='3400', max_length=5, verbose_name='At what altitude would you like to jump from a plane?'),
        ),
    ]
