# Generated by Django 5.1.5 on 2025-02-20 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_subscriber_altitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Event time')),
                ('maxSubscribers', models.PositiveIntegerField(default=0, verbose_name='Max number of subscribers')),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_times', to='event.eventdate')),
            ],
            options={
                'verbose_name': 'Event Time',
                'verbose_name_plural': 'Event Times',
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='eventTime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='event.eventtime', verbose_name='Event Time'),
            preserve_default=False,
        ),
    ]
