# Generated by Django 5.1.5 on 2025-02-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_eventtime_subscriber_eventtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdate',
            name='maxSubscribers',
        ),
    ]
