# Generated by Django 5.1.5 on 2025-03-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_remove_eventdate_maxsubscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtime',
            options={'ordering': ['time'], 'verbose_name': 'Event Time', 'verbose_name_plural': 'Event Times'},
        ),
        migrations.AlterUniqueTogether(
            name='eventtime',
            unique_together={('event_date', 'time')},
        ),
    ]
