# Generated by Django 5.1.5 on 2025-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_eventtime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='maxSubscribers',
            field=models.PositiveIntegerField(default=6, verbose_name='Max number of subscribers'),
        ),
    ]
