# Generated by Django 5.1.5 on 2025-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_eventtime_maxsubscribers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventtime',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventtime',
            constraint=models.UniqueConstraint(fields=('event_date', 'time'), name='unique_event_time'),
        ),
    ]
