# Generated by Django 5.1.5 on 2025-03-05 21:10

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_subscriber_eventdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='birthDate_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birthDate',
            field=birthday.fields.BirthdayField(verbose_name='Birth Date'),
        ),
    ]
